apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: k8s/secret
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: k8s/secret
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: k8s/secret
        property: MYSQL_DATABASE
    - secretKey: MYSQL_USER
      remoteRef:
        key: k8s/secret
        property: MYSQL_USER
